version: '3.8'

services:
  # PostgreSQL Veritabanı
  postgres:
    image: postgres:13
    container_name: iot_postgres
    environment:
      POSTGRES_DB: iot_sensors
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    networks:
      - iot_network

  # MQTT Broker (Mosquitto)
  mosquitto:
    image: eclipse-mosquitto:2.0
    container_name: iot_mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
      - mosquitto_data:/mosquitto/data
      - mosquitto_logs:/mosquitto/log
    restart: unless-stopped
    networks:
      - iot_network

  # pgAdmin (Veritabanı yönetimi için opsiyonel)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: iot_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@iot.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - iot_network

volumes:
  postgres_data:
  mosquitto_data:
  mosquitto_logs:
  pgadmin_data:

networks:
  iot_network:
    driver: bridge 